# Generated by Django 4.2.3 on 2023-07-29 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_age_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/avatar.png', upload_to=users.services.get_path_upload_user_avatar, validators=[users.services.validate_size_image]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
