# Generated by Django 4.2.3 on 2023-08-02 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vacancy.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vacancy.services.get_path_images_vacancy, validators=[vacancy.services.validate_size_image_vacancy])),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('profit', models.CharField(blank=True, default='Не указано', max_length=50)),
                ('contact', models.ManyToManyField(limit_choices_to=10, to='vacancy.contact')),
                ('image', models.ManyToManyField(blank=True, limit_choices_to=5, to='vacancy.imagevacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
