# Generated by Django 4.2.3 on 2023-08-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_remove_vacancy_image_imagevacancy_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy'),
            preserve_default=False,
        ),
    ]
